source 'https://rubygems.org'
gem 'colorize'
gem 'country_lookup'
gem 'gemspec'
gem 'httparty'
gem 'nokogiri'
gem 'rack', '~>1.1'
gem 'rspec', require: 'spec'
gem 'rubocop'
gem 'telegram-bot-ruby'
gem 'vcr'